#!/usr/bin/env python3
import click
import time
import d3b_cli_igor.common, d3b_cli_igor.log_ops.app_logs, d3b_cli_igor.app_ops.ecs_deployment, d3b_cli_igor.deploy_ops.deploy, d3b_cli_igor.deploy_ops.generate_config, d3b_cli_igor.utils.shortcuts, d3b_cli_igor.utils.diff
import boto3


@click.group()
def igor_cli():
    pass

@click.command(name="get-logs")
@click.option(
    "--app",
    nargs=1,
    required=True,
    help="Enter Application Name",
)
@click.option(
    "--environment", nargs=1, required=True, help="Specify AWS Account Number"
)
@click.option(
    "--query",
    nargs=1,
    default="fields @timestamp, @message | sort @timestamp desc | limit 20",
    required=False,
    help="Enter Query",
)
@click.option(
    "--hours",
    nargs=1,
    default=0.5,
    required=False,
    help="How far back in hours you want to go",
)
def get_logs(app, environment, query, hours):
    d3b_cli_igor.log_ops.app_logs.get_app_logs(app, environment, query, hours)


@click.command(name="deploy")
@click.option("--account_name", nargs=1, required=True)
@click.option("--organization", nargs=1, required=True)
@click.option("--region", nargs=1, required=True)
@click.option("--environment", nargs=1, required=True)
@click.option("--config_file", nargs=1, default="Jenkinsfile", required=False)
@click.option("--mode", nargs=1, default="deploy", required=False)
def deploy(account_name, organization, region, environment, config_file, mode):
    d3b_cli_igor.deploy_ops.deploy.deploy(
        account_name, organization, region, environment, config_file, mode
    )

@click.command(name="shortcuts")
@click.option("--name", nargs=1, required=False)
@click.option("--browser_type", default="", nargs=1, required=False)
@click.option("--show", is_flag=True, required=False)
def shortcuts(name, browser_type, show):
    d3b_cli_igor.utils.shortcuts.browser(name, browser_type, show)

@click.command(name="check_build")
@click.option("--account", nargs=1, required=True)
def check_build(account):
    d3b_cli_igor.utils.shortcuts.check_build(account)

@click.command(name="onboarding")
@click.option("--role", nargs=1, required=True)
@click.option("--install_os", default="mac", nargs=1, required=False)
def onboarding(role,install_os):
    d3b_cli_igor.utils.shortcuts.onboarding(role,install_os)

@click.command(name="awslogin")
def awslogin():
    d3b_cli_igor.utils.shortcuts.awslogin()


@click.command(name="dev_env_tunnel")
@click.option("--environment", nargs=1, required=True)
@click.option("--cidr_block", nargs=1, default="", required=False)
def dev_env_tunnel(environment,cidr_block):
    d3b_cli_igor.utils.shortcuts.dev_env_tunnel(environment,cidr_block)

@click.command(name="diff")
@click.option(
    "--file1",
    nargs=1,
    required=True,
    help="Enter File Path For File 1",
)
@click.option(
    "--file2",
    nargs=1,
    required=True,
    help="Enter File Path For File 2",
)
def diff(file1,file2):
    d3b_cli_igor.utils.diff.diff_files(file1,file2)

@click.command(name="split_files")
@click.option(
    "--file_to_split",
    nargs=1,
    required=True,
    help="Enter File Path to the File",
)
@click.option(
    "--num_of_lines",
    nargs=1,
    required=True,
    help="Enter Enter Number of line for each split file",
)
def split_files(file_to_split,num_of_lines):
    d3b_cli_igor.utils.diff.split_files(file_to_split,num_of_lines)

@click.command(name="restart")
@click.option(
    "--app",
    nargs=1,
    required=True,
    help="Enter Application Name",
)
@click.option("--environment", nargs=1, required=True, help="Specify Environment")
@click.option("--account", nargs=1, required=True, help="Specify AWS Account")
def restart(app, environment, account):
    d3b_cli_igor.app_ops.ecs_deployment.restart(app, environment, account)


@click.command(name="generate-tf-module-files")
@click.option('--project',nargs=1,required=True)
@click.option('--region',nargs=1,required=True)
@click.option('--account_name',nargs=1,required=True)
@click.option('--environment',nargs=1,required=True)
@click.option('--module',nargs=1,required=True)
def generate_tf_module_files(project,region,account_name,environment,module):
    d3b_cli_igor.deploy_ops.generate_config.generate_tf_module_files(project,region,account_name, environment,module)


igor_cli.add_command(get_logs)
igor_cli.add_command(restart)
igor_cli.add_command(deploy)
igor_cli.add_command(generate_tf_module_files)
igor_cli.add_command(shortcuts)
igor_cli.add_command(check_build)
igor_cli.add_command(onboarding)
igor_cli.add_command(awslogin)
igor_cli.add_command(dev_env_tunnel)
igor_cli.add_command(diff)
igor_cli.add_command(split_files)


if __name__ == "__main__":
    igor_cli()
