#!/usr/bin/env python3
import click
import time
import d3b_cli_igor.common, d3b_cli_igor.log_ops.app_logs, d3b_cli_igor.app_ops.ecs_deployment, d3b_cli_igor.deploy_ops.deploy, d3b_cli_igor.deploy_ops.generate_config
import boto3


@click.group()
def igor_cli():
    pass


@click.command(name="get-logs")
@click.option(
    "--app",
    nargs=1,
    required=True,
    help="Enter Application Name",
)
@click.option(
    "--environment", nargs=1, required=True, help="Specify AWS Account Number"
)
@click.option(
    "--query",
    nargs=1,
    default="fields @timestamp, @message | sort @timestamp desc | limit 20",
    required=False,
    help="Enter Query",
)
@click.option(
    "--hours",
    nargs=1,
    default=3,
    required=False,
    help="How far back in hours you want to go",
)
def get_logs(app, environment, query, hours):
    d3b_cli_igor.log_ops.app_logs.get_app_logs(app, environment, query, hours)


@click.command(name="deploy")
@click.option("--account_name", nargs=1, required=True)
@click.option("--organization", nargs=1, required=True)
@click.option("--region", nargs=1, required=True)
@click.option("--environment", nargs=1, required=True)
@click.option("--config_file", nargs=1, default="Jenkinsfile", required=False)
@click.option("--mode", nargs=1, default="deploy", required=False)
def deploy(account_name, organization, region, environment, config_file, mode):
    d3b_cli_igor.deploy_ops.deploy.deploy(
        account_name, organization, region, environment, config_file, mode
    )


@click.command(name="restart")
@click.option(
    "--app",
    nargs=1,
    required=True,
    help="Enter Application Name",
)
@click.option("--environment", nargs=1, required=True, help="Specify Environment")
@click.option("--account", nargs=1, required=True, help="Specify AWS Account")
def restart(app, environment, account):
    d3b_cli_igor.app_ops.ecs_deployment.restart(app, environment, account)


@click.command()
@click.option('--project',nargs=1,required=True)
@click.option('--region',nargs=1,required=True)
@click.option('--account_name',nargs=1,required=True)
@click.option('--environment',nargs=1,required=True)
@click.option('--module',nargs=1,required=True)
def generate_tf_module_files(project,region,account_name,environment,module):
    d3b_cli_igor.deploy_ops.generate_config.generate_tf_module_files(project,region,account_name, environment,module)


igor_cli.add_command(get_logs)
igor_cli.add_command(restart)
igor_cli.add_command(deploy)
igor_cli.add_command(generate_tf_module_files)

if __name__ == "__main__":
    igor_cli()
